// ============================================================
// GET /api/analytics/cross-platform?company=MBC|MBI|ALL
//
// Powers the dashboard's Cross-Platform CPL widget, which has always
// called this route — it was never implemented, so `r.json()` threw on the
// 404 page and the widget rendered nothing (and, with no .catch, logged an
// unhandled rejection on every dashboard load).
//
// Numbers are delegated to /api/dashboard/unified so this widget can never
// disagree with the Unified Overview card sitting next to it.
//
// The recommendation is computed here, deterministically, from those same
// numbers — not generated by Gemini. A dashboard widget that fires an LLM
// call on every page load is a silent token burner, and the comparison is
// simple arithmetic that does not need one.
// ============================================================
import { NextRequest, NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth";
import { canAccessCompany } from "@/lib/permissions";

import { assessCoverage, type PlatformOutcome } from "@/lib/cross-platform-outcome";
import { readGroup } from "@/lib/odoo-client";
import { isCompany } from "@/lib/companies"

export const dynamic = "force-dynamic";

type Scope = string /* mã công ty hoặc "ALL" */;

interface UnifiedPlatform {
  spend?: number;
  leads?: number;
  clicks?: number;
  error?: string | null;
}

// NOTE the nesting: /api/dashboard/unified returns the per-channel figures
// under `summary`, and per-channel errors under `breakdown` (facebook uses
// `error`, google uses `gg.error`). Reading them off the top level yields
// undefined, which silently renders as ₫0 / 0 conversions.
interface UnifiedResponse {
  summary?: {
    facebook?: UnifiedPlatform & { leadsBasis?: string };
    google?: UnifiedPlatform & { leadsBasis?: string };
    insight?: { comparable?: boolean };
  };
  breakdown?: Array<{ channel?: string; error?: string | null; gg?: { error?: string } | null }>;
}

const vnd = (n: number) => new Intl.NumberFormat("vi-VN").format(Math.round(n));

function buildRecommendation(
  fb: { spend: number; conversions: number; cpl: number | null },
  gg: { spend: number; conversions: number; cpl: number | null },
  comparable: boolean,
  basis: { fb?: string; gg?: string },
): string {
  // Facebook counts lead actions; Google counts every enabled conversion
  // action. Ranking those two CPLs against each other rewards whichever
  // platform counts more event types, so no budget advice is given until
  // the definitions are aligned — see app/api/dashboard/unified/route.ts.
  if (!comparable && fb.cpl !== null && gg.cpl !== null) {
    return `Facebook ₫${vnd(fb.cpl)}/lead và Google ₫${vnd(gg.cpl)}/lead chưa so sánh trực tiếp được — ` +
      `Facebook tính ${(basis.fb ?? "hành động dạng lead").toLowerCase()}, Google tính ${(basis.gg ?? "mọi conversion action").toLowerCase()}. ` +
      `Cần thống nhất đâu là "lead" cho Google trước khi dịch chuyển ngân sách.`;
  }
  if (fb.cpl === null && gg.cpl === null) {
    return "Chưa có chuyển đổi nào ở cả hai nền tảng trong 7 ngày qua — chưa đủ dữ liệu để so sánh CPL.";
  }
  if (fb.cpl === null) {
    return `Facebook chưa ghi nhận chuyển đổi nào trong 7 ngày qua (đã chi ₫${vnd(fb.spend)}). Google đang ở mức ₫${vnd(gg.cpl!)}/lead — nên kiểm tra tracking của Facebook trước khi so sánh.`;
  }
  if (gg.cpl === null) {
    return `Google chưa ghi nhận chuyển đổi nào trong 7 ngày qua (đã chi ₫${vnd(gg.spend)}). Facebook đang ở mức ₫${vnd(fb.cpl)}/lead — nên kiểm tra tracking của Google trước khi so sánh.`;
  }

  const cheaper = fb.cpl <= gg.cpl ? "Facebook" : "Google";
  const dearer = cheaper === "Facebook" ? "Google" : "Facebook";
  const lo = Math.min(fb.cpl, gg.cpl);
  const hi = Math.max(fb.cpl, gg.cpl);
  const gapPct = lo > 0 ? ((hi - lo) / lo) * 100 : 0;

  if (gapPct < 15) {
    return `CPL hai nền tảng chênh nhau ${gapPct.toFixed(0)}% (₫${vnd(fb.cpl)} vs ₫${vnd(gg.cpl)}) — khác biệt chưa đáng kể, chưa cần dịch chuyển ngân sách.`;
  }

  return `${cheaper} đang rẻ hơn ${gapPct.toFixed(0)}% (₫${vnd(lo)} so với ₫${vnd(hi)}/lead). Cân nhắc dịch một phần ngân sách từ ${dearer} sang ${cheaper}, kiểm tra khả năng mở rộng trước khi tăng mạnh.`;
}

/**
 * Đếm đơn Odoo gắn về từng nền tảng trong 90 ngày.
 *
 * Dùng 90 ngày chứ không 7 như phần trên: độ phủ gắn thẻ là đặc tính của quy
 * trình, không phải của tuần này. Bảy ngày quá ít để kết luận "Facebook không
 * gắn thẻ" — có thể chỉ là tuần đó không ai chạy.
 *
 * `readGroup` để ĐẾM, không phải `searchRead`: tham số thứ 5 của searchRead là
 * object {limit,...}, truyền số trần sẽ rơi về mặc định 200 và mọi tỷ lệ tính
 * ra đều sai. Đã mắc bẫy này một lần ngày 24/09.
 */
async function buildCoverage(
  scope: Scope, fbSpend: number, ggSpend: number,
): Promise<ReturnType<typeof assessCoverage>> {
  const since = new Date(Date.now() - 90 * 86400000).toISOString().slice(0, 19).replace("T", " ");
  // `readGroup` nhận `unknown[][]` (mảng các tuple), khác `searchRead` nhận
  // `unknown[]` phẳng vì nó còn cho phép chèn toán tử "|"/"&" dạng chuỗi trần.
  const domain: unknown[][] = [
    ["date_order", ">=", since],
    ["state", "in", ["sale", "done"]],
    ["source_id", "!=", false],
  ];
  const rows = (await readGroup("sale.order", domain, ["amount_total:sum"], ["source_id"])) as Array<
    Record<string, unknown>
  >;

  // Odoo có NHIỀU cách viết cho cùng một nguồn (`facebook_ads`, `facebook-ads`,
  // `facebook`, `facebookmatbao` — đếm được 4 biến thể ngày 24/09). Gom bằng
  // khớp mẫu chứ không so bằng nhau, nếu không sẽ đếm thiếu.
  const tally = (re: RegExp) => {
    let orders = 0, revenue = 0;
    for (const r of rows) {
      const src = r.source_id;
      const name = Array.isArray(src) ? String(src[1] ?? "") : String(src ?? "");
      if (!re.test(name)) continue;
      orders += Number(r.__count ?? 0);
      revenue += Number(r.amount_total ?? 0);
    }
    return { orders, revenue };
  };
  const g = tally(/google/i);
  const f = tally(/facebook|meta\b/i);

  const mkOutcome = (
    platform: "google" | "facebook", spendVnd: number, t: { orders: number; revenue: number },
  ): PlatformOutcome => ({
    platform, source: "odoo", spendVnd, taggedOrders: t.orders, taggedRevenueVnd: t.revenue,
  });

  void scope; // độ phủ tính trên toàn tài khoản, không tách công ty
  return assessCoverage(mkOutcome("google", ggSpend, g), mkOutcome("facebook", fbSpend, f));
}

export async function GET(request: NextRequest) {
  const user = await getCurrentUser();
  if (!user) return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 });

  const raw = (request.nextUrl.searchParams.get("company") ?? "ALL").toUpperCase();
  const scope: Scope = isCompany(raw) ? raw : "ALL";
  if (scope !== "ALL" && !canAccessCompany(user.role, scope)) {
    return NextResponse.json({ success: false, error: "Access denied for this company" }, { status: 403 });
  }

  const to = new Date().toISOString().split("T")[0];
  const from = new Date(Date.now() - 7 * 86400000).toISOString().split("T")[0];

  try {
    const base = `http://localhost:${process.env.PORT || 3000}`;
    const res = await fetch(
      `${base}/api/dashboard/unified?company=${scope}&from=${from}&to=${to}`,
      { headers: { cookie: request.headers.get("cookie") ?? "" } },
    );
    if (!res.ok) throw new Error(`/api/dashboard/unified → HTTP ${res.status}`);
    const unified = (await res.json()) as UnifiedResponse;

    const summary = unified.summary;
    if (!summary) throw new Error("/api/dashboard/unified không trả về summary");

    // A platform that errored upstream must not be shown as ₫0 — that reads
    // as "spent nothing", which is a different fact from "could not fetch".
    const fbErr = unified.breakdown?.find((b) => b.channel === "facebook")?.error ?? null;
    const ggErr = unified.breakdown?.find((b) => b.channel === "google")?.gg?.error ?? null;
    const upstreamErrors = [
      fbErr ? `Facebook: ${fbErr}` : null,
      ggErr ? `Google: ${ggErr}` : null,
    ].filter(Boolean) as string[];

    if (upstreamErrors.length === 2) {
      return NextResponse.json(
        { success: false, error: `Không lấy được dữ liệu — ${upstreamErrors.join("; ")}` },
        { status: 502 },
      );
    }

    const mk = (p: UnifiedPlatform | undefined) => {
      const spend = p?.spend ?? 0;
      const conversions = p?.leads ?? 0;
      return { spend, conversions, cpl: conversions > 0 ? spend / conversions : null };
    };

    const fb = mk(summary.facebook);
    const gg = mk(summary.google);
    const comparable = summary.insight?.comparable === true;

    return NextResponse.json({
      success: true,
      company: scope,
      period: { from, to },
      data: {
        // The widget divides by these, so send 0 rather than null; `cplKnown`
        // tells it whether the 0 means "no conversions yet".
        facebook: { spend: fb.spend, conversions: fb.conversions, cpl: fb.cpl ?? 0, cplKnown: fb.cpl !== null },
        google: { spend: gg.spend, conversions: gg.conversions, cpl: gg.cpl ?? 0, cplKnown: gg.cpl !== null },
        comparable,
        recommendation: buildRecommendation(fb, gg, comparable, {
          fb: summary.facebook?.leadsBasis,
          gg: summary.google?.leadsBasis,
        }),
        partialErrors: upstreamErrors,
      },
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Lỗi không xác định";
    console.error("[analytics/cross-platform]", err);
    return NextResponse.json({ success: false, error: message }, { status: 502 });
  }
}
