// ============================================================
// Module Registry — Default Definitions
//
// These are the canonical module definitions that exactly
// reproduce current sidebar behaviour.  They are the fallback
// when no data/modules.json override exists for a module.
//
// Maintain parity with components/Sidebar.tsx navItems.
// ============================================================

import type { ModuleDefinition } from "./types";

const ADMIN_ROLES = ["super_admin", "admin_mbc", "admin_mbi", "admin"] as const; // Đợt 21 A5: + vai trò chung

export const DEFAULT_MODULES: ModuleDefinition[] = [
  // ── Core (visible to all roles) ────────────────────────
  {
    id:            "dashboard",
    label:         "Dashboard",
    href:          "/",
    iconName:      "LayoutDashboard",
    order:         10,
    navVisible:    true,
    enabled:       true,
    tenantDefault: true,
    settingsDomains: [],
  },
  {
    id:            "campaigns",
    label:         "Campaigns",
    href:          "/campaigns",
    iconName:      "Megaphone",
    order:         20,
    navVisible:    true,
    enabled:       true,
    tenantDefault: true,
    settingsDomains: ["budget"],
  },

  // ── Admin-only modules ─────────────────────────────────
  {
    id:            "creative",
    label:         "Creative AI",
    href:          "/creative",
    iconName:      "Sparkles",
    order:         30,
    navVisible:    true,
    enabled:       true,
    requiredRoles: [...ADMIN_ROLES],
    tenantDefault: true,
    requiredConnectors: ["gemini", "meta"],
    settingsDomains:  ["credentials_gemini", "credentials_meta"],
  },
  {
    id:            "visual-analysis",
    label:         "Creative Library",
    href:          "/creative/analysis",
    iconName:      "Eye",
    order:         35,
    navVisible:    true,
    enabled:       true,
    requiredRoles: [...ADMIN_ROLES],
    requiredModules: ["creative"],
    tenantDefault: true,
    requiredConnectors: ["meta"],
  },
  {
    id:            "intelligence",
    label:         "Intelligence",
    href:          "/intelligence",
    iconName:      "Target",
    order:         40,
    navVisible:    true,
    enabled:       true,
    requiredRoles: [...ADMIN_ROLES],
    tenantDefault: true,
    settingsDomains: ["kpi"],
  },
  {
    id:            "google-pmax",
    label:         "PMax Insights",
    href:          "/google-pmax",
    iconName:      "PieChart",
    order:         50,
    navVisible:    true,
    enabled:       true,
    requiredRoles: [...ADMIN_ROLES],
    tenantDefault: true,
    requiredConnectors: ["google"],
    settingsDomains: ["credentials_google"],
  },
  {
    id:            "google-audit",
    label:         "Google Audit",
    href:          "/google-audit",
    iconName:      "ShieldCheck",
    order:         60,
    navVisible:    true,
    enabled:       true,
    requiredRoles: [...ADMIN_ROLES],
    tenantDefault: true,
    requiredConnectors: ["google"],
  },
  {
    id:            "improvements",
    label:         "Improvements",
    href:          "/improvements",
    iconName:      "Lightbulb",
    order:         70,
    navVisible:    true,
    enabled:       true,
    requiredRoles: [...ADMIN_ROLES],
    tenantDefault: true,
    badge:         "improvements",
  },
  {
    id:            "automation",
    label:         "Automation",
    href:          "/automation",
    iconName:      "Zap",
    order:         80,
    navVisible:    true,
    enabled:       true,
    requiredRoles: [...ADMIN_ROLES],
    tenantDefault: true,
  },
  {
    id:            "toolkit",
    label:         "Toolkit",
    href:          "/toolkit",
    iconName:      "Wrench",
    order:         90,
    navVisible:    true,
    enabled:       true,
    requiredRoles: [...ADMIN_ROLES],
    tenantDefault: true,
    children: [
      { id: "toolkit-ngram",    label: "N-Gram Finder",     href: "/toolkit/ngram" },
      { id: "toolkit-daypart",  label: "Day-Parting",       href: "/toolkit/dayparting" },
      { id: "toolkit-pacing",   label: "💰 Budget Pacing",  href: "/toolkit/budget-pacing" },
      { id: "toolkit-qs",       label: "🎯 Quality Score",  href: "/toolkit/quality-score" },
      { id: "toolkit-segments", label: "📊 Phân khúc Bid",  href: "/toolkit/segments" },
    ],
  },
  {
    id:            "audiences",
    label:         "Audiences",
    href:          "/audiences",
    iconName:      "Users",
    order:         100,
    navVisible:    true,
    enabled:       true,
    requiredRoles: [...ADMIN_ROLES],
    tenantDefault: true,
    requiredConnectors: ["meta"],
  },

  // ── Shared (all roles) ─────────────────────────────────
  {
    id:            "reports",
    label:         "Reports",
    href:          "/reports",
    iconName:      "BarChart2",
    order:         110,
    navVisible:    true,
    enabled:       true,
    tenantDefault: true,
    settingsDomains: [],
  },
  {
    id:            "notifications",
    label:         "Thông báo",
    href:          "/notifications",
    iconName:      "Bell",
    order:         120,
    navVisible:    true,
    enabled:       true,
    tenantDefault: true,
    settingsDomains: ["notifications"],
  },
  {
    id:            "guide",
    label:         "Hướng dẫn",
    href:          "/guide",
    iconName:      "BookOpen",
    order:         130,
    navVisible:    true,
    enabled:       true,
    tenantDefault: true,
  },
  {
    id:            "settings",
    label:         "Settings",
    href:          "/settings",
    iconName:      "Settings",
    order:         140,
    navVisible:    true,
    enabled:       true,
    tenantDefault: true,
    settingsDomains: ["budget", "credentials_meta", "credentials_google", "credentials_gemini", "credentials_telegram", "revenue", "cpl_thresholds", "users", "team", "notifications", "tracking", "kpi"],
    children: [
      {
        id:            "settings-users",
        label:         "Quản lý Users",
        href:          "/settings/users",
        requiredRoles: ["super_admin"],
      },
    ],
  },

  // ── Pre-registered (currently disabled / commented out) ─
  {
    id:            "ai-ad-copy",
    label:         "AI Ad Copy",
    href:          "/creative/ad-copy",
    iconName:      "PenTool",
    order:         32,
    navVisible:    false,    // hidden until enabled
    enabled:       false,
    requiredRoles: [...ADMIN_ROLES],
    requiredModules: ["creative"],
    tenantDefault: false,
  },
  {
    id:            "competitors",
    label:         "Competitor Spy",
    href:          "/competitors",
    iconName:      "Search",
    order:         45,
    navVisible:    false,
    enabled:       false,
    requiredRoles: [...ADMIN_ROLES],
    tenantDefault: false,
  },
  {
    id:            "ab-testing",
    label:         "A/B Testing",
    href:          "/automation/ab-testing",
    iconName:      "Beaker",
    order:         85,
    navVisible:    false,
    enabled:       false,
    requiredRoles: [...ADMIN_ROLES],
    requiredModules: ["automation"],
    tenantDefault: false,
  },
  {
    id:            "cpl",
    label:         "CPL",
    href:          "/cpl",
    iconName:      "Target",
    order:         25,
    navVisible:    false,
    enabled:       false,
    tenantDefault: false,
    settingsDomains: ["cpl_thresholds"],
  },
];
