// ============================================================
// Job registry — static descriptor for every cron job
// Source of truth for schedules, risk level, required env.
// ============================================================

import type { JobId, JobRiskLevel, JobSchedulingStatus } from "./types";

export interface JobDescriptor {
  id: JobId;
  displayName: string;
  description: string;
  /** Cron expression (UTC) — real schedule if schedulingStatus is "auto"
   *  (see docker-entrypoint.sh), intended/candidate schedule otherwise. */
  cronExpr: string;
  /** Human-readable interval for display */
  intervalLabel: string;
  riskLevel: JobRiskLevel;
  /** Real endpoint path — every entry in this registry has a route.ts that
   *  actually exists (verified 2026-07-13; 6 entries pointing at
   *  non-existent routes were removed rather than kept as dead weight). */
  endpoint: string;
  /** The endpoint's real exported HTTP method — app/api/jobs/[id]/trigger
   *  used to hardcode GET regardless, which silently 405'd for the 3
   *  POST-only routes (automation_sim_apply, decision_memory_eval,
   *  weekly_report) every time someone clicked "Run" for them. Fixed
   *  2026-07-13 by making the trigger route read this field. */
  httpMethod: "GET" | "POST";
  /** Env vars that must be set for this job to run */
  requiredEnv: string[];
  /** Whether this job can be manually triggered via the jobs API */
  manualTriggerAllowed: boolean;
  /** Default max duration in seconds (mirrors maxDuration export) */
  maxDurationSec: number;
  /** Short note about what "high risk" means for this job */
  riskNote?: string;
  /** "auto" = wired into docker-entrypoint.sh's crontab; "manual_only" =
   *  real route, deliberately not auto-scheduled. /settings/jobs renders
   *  this explicitly so admins never have to guess whether a job is
   *  actually running unattended. */
  schedulingStatus: JobSchedulingStatus;
  /** 29/09: job ĐÃ NGỪNG (lý do) — không hiện ở trang Jobs, không điều phối, không canh. Route + code giữ nguyên (tính năng khác
   *  vẫn gọi được, vd tab Tự động hoá); bỏ dòng này là bật lại. */
  retired?: string;
}

export const JOB_REGISTRY: JobDescriptor[] = [
  {
    id: "playbook_meta_sync",
    displayName: "Sổ kinh nghiệm — tải số Meta theo khoảng 15 ngày",
    description: "Làm mới khoảng 15 ngày hiện tại + tải một khoảng cũ còn thiếu (đủ 180 ngày sau ~11 đêm)",
    cronExpr: "30 20 * * *",
    intervalLabel: "Hằng ngày 03:30 giờ VN (20:30 UTC)",
    riskLevel: "low",
    endpoint: "/api/cron/playbook-meta-sync",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET"],
    manualTriggerAllowed: true,
    maxDurationSec: 300,
    riskNote: "chỉ đọc Meta (~10 lượt gọi/đêm); ghi data/playbook/meta-chunks/",
    schedulingStatus: "auto",
  },
  {
    id: "playbook_extract",
    displayName: "Sổ kinh nghiệm — bóc kinh nghiệm hằng tuần",
    description: "Chấm thắng/thua 180 ngày (Meta từ khoảng đã tải + Google), cập nhật Sổ kinh nghiệm, giữ quyết định Duyệt/Bỏ của người",
    cronExpr: "0 21 * * 0",
    intervalLabel: "Thứ Hai 04:00 giờ VN (Chủ nhật 21:00 UTC)",
    riskLevel: "low",
    endpoint: "/api/cron/playbook-extract",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET"],
    manualTriggerAllowed: true,
    maxDurationSec: 300,
    riskNote: "chỉ đọc Meta (2 lượt) + Google Ads (~40 truy vấn); ghi data/playbook/<công ty>.json",
    schedulingStatus: "auto",
  },
  {
    id: "pmax_auto_controls",
    displayName: "PMax tự động — áp việc ít rủi ro đã bật",
    description: "Tính lại đề xuất kiểm soát PMax 30 ngày; chỉ áp loại việc người dùng BẬT (phủ định đối thủ 0 đơn / loại app di động / loại trang mở rộng 0 đơn), tối đa 20 việc/ngày/công ty; Kiểm trước → ghi → đọc lại → báo Teams; hoàn tác ở X-quang",
    cronExpr: "0 1 * * *",
    intervalLabel: "Hằng ngày 08:00 giờ VN (01:00 UTC)",
    riskLevel: "medium",
    endpoint: "/api/cron/pmax-auto-controls",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET"],
    manualTriggerAllowed: true,
    maxDurationSec: 300,
    riskNote: "GHI lên Google Ads (phủ định cấp chiến dịch, loại vị trí cấp tài khoản, loại trang) — chỉ khi đã bật trong X-quang; mặc định tắt",
    schedulingStatus: "auto",
  },
  {
    id: "pmax_experiments",
    displayName: "Thí nghiệm vùng PMax — đo lại / tự kết thúc",
    description: "Đo lại thí nghiệm loại trừ vùng đang chạy (đơn vùng tắt so với vùng đối chứng theo tuần); tới ngày hẹn thì TỰ gỡ loại trừ + trả vùng nhắm cũ và báo Teams",
    cronExpr: "0 2 * * *",
    intervalLabel: "Hằng ngày 09:00 giờ VN (02:00 UTC)",
    riskLevel: "medium",
    endpoint: "/api/cron/pmax-experiments",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET"],
    manualTriggerAllowed: true,
    maxDurationSec: 300,
    riskNote: "GHI lên Google Ads chỉ khi thí nghiệm tới hạn: gỡ loại trừ vùng tool đã thêm, trả nhắm cũ; không có thí nghiệm thì chỉ đọc",
    schedulingStatus: "auto",
  },
  {
    id: "lead_quality_upload",
    displayName: "Chất lượng lead → Google (gửi lại)",
    description: "Gửi các sự kiện lead đạt chuẩn / chốt đơn đang chờ hoặc lỗi tạm lên Google Ads (chuyển đổi offline, tối đa 3 lần mỗi sự kiện)",
    cronExpr: "20 * * * *",
    intervalLabel: "Mỗi giờ (phút 20)",
    riskLevel: "low",
    endpoint: "/api/cron/lead-quality-upload",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET"],
    manualTriggerAllowed: true,
    maxDurationSec: 300,
    riskNote: "GHI chuyển đổi offline vào hành động PHỤ do tool tạo (không đổi đặt giá tới khi người dùng đưa vào mục tiêu); không có sự kiện thì không làm gì",
    schedulingStatus: "auto",
  },
  {
    id: "split_tracking",
    displayName: "Theo dõi bản tách Search (Đợt 18)",
    description: "Mỗi sáng: bản tách đã chuyển từ khoá tới mốc 7 / 14 ngày thì tự đo và lưu kết quả; 'Nên hoàn tác' → Teams kênh Ads + Hộp việc. Nhắc bản tách đã tạo > 3 ngày mà chưa chuyển / chiến dịch mới còn tạm dừng",
    cronExpr: "20 1 * * *",
    intervalLabel: "Hằng ngày 08:20 (giờ VN)",
    riskLevel: "low",
    endpoint: "/api/cron/split-tracking",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET"],
    manualTriggerAllowed: true,
    maxDurationSec: 300,
    riskNote: "Chỉ đọc Google Ads + ghi kết quả đo vào bản ghi tách + gửi Teams. Không đổi gì trên tài khoản quảng cáo",
    schedulingStatus: "auto",
  },
  {
    id: "query_smoke",
    displayName: "Tự kiểm truy vấn thật (Đợt 20a)",
    description: "Mỗi sáng chạy thử (chỉ đọc, khoảng 1 ngày) các hàm đọc Google Ads / Meta mà tính năng đang dùng — X-quang Search/PMax/Meta, tài sản + quảng cáo + diễn biến bản tách, so sánh đơn thật Google/Meta, nguồn đơn. Hỏng (lỗi MỚI) hoặc đã hết lỗi → Teams kênh IT",
    cronExpr: "45 22 * * *",
    intervalLabel: "Hằng ngày 05:45 (giờ VN)",
    riskLevel: "low",
    endpoint: "/api/cron/query-smoke",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET"],
    manualTriggerAllowed: true,
    maxDurationSec: 300,
    riskNote: "Chỉ đọc Google Ads / Meta (khoảng 1 ngày, ~20 truy vấn mỗi công ty). Không ghi gì lên tài khoản quảng cáo",
    schedulingStatus: "auto",
  },
  {
    id: "real_orders_sync",
    displayName: "Đơn thật → Google & Meta (Đợt 16)",
    description: "Đọc đơn MBI đã thu tiền trong Odoo (30 ngày), đưa vào hàng chuyển đổi offline Google (\"Lead chốt đơn\") và gửi Meta Conversions API (sự kiện DonThanhToanOdoo, 7 ngày) — chỉ nền tảng nào đã bật",
    cronExpr: "5 */3 * * *",
    intervalLabel: "3 giờ một lần (phút 5)",
    riskLevel: "medium",
    endpoint: "/api/cron/real-orders-sync",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET"],
    manualTriggerAllowed: true,
    maxDurationSec: 300,
    riskNote: "Mặc định TẮT cả hai nền tảng (bật ở Đo lường → Đơn thật, cần XAC NHAN). Google: hành động PHỤ, không đổi đặt giá. Meta: sự kiện riêng, không trùng Purchase; có mã thử thì chỉ vào tab Kiểm tra sự kiện",
    schedulingStatus: "auto",
  },
  {
    id: "numbers_check",
    displayName: "Đối chiếu số hằng tuần — trang tool vs nguồn gốc",
    description: "Thứ Hai 09:30: so chi Google (Tổng quan, X-quang Search, X-quang PMax) và chi Meta (X-quang Meta) 7 ngày với truy vấn gốc Google/Meta; lệch > 5% báo Teams IT",
    cronExpr: "30 2 * * 1",
    intervalLabel: "Thứ Hai 09:30 giờ VN (02:30 UTC)",
    riskLevel: "low",
    endpoint: "/api/cron/numbers-check",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET"],
    manualTriggerAllowed: true,
    maxDurationSec: 300,
    riskNote: "chỉ đọc Google Ads (~10 truy vấn/công ty) + Meta (~5 lượt gọi); ghi data/numbers-check.json",
    schedulingStatus: "auto",
  },
  {
    id: "system_morning",
    displayName: "Báo sáng hệ thống — sức khoẻ tool",
    description: "08:05 mỗi ngày gửi Teams kênh IT: job lỗi / lỡ lịch / chưa từng chạy, kết nối hỏng, hôm qua tool ghi gì lên tài khoản quảng cáo, thí nghiệm đang chạy — gửi cả khi ổn",
    cronExpr: "5 1 * * *",
    intervalLabel: "Hằng ngày 08:05 giờ VN (01:05 UTC)",
    riskLevel: "low",
    endpoint: "/api/cron/system-morning",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET"],
    manualTriggerAllowed: true,
    maxDurationSec: 60,
    riskNote: "chỉ đọc dữ liệu nội bộ (lịch sử job, sức khoẻ kết nối, nhật ký ghi); gửi 1 thẻ Teams",
    schedulingStatus: "auto",
  },
  {
    id: "inbox_build",
    displayName: "Dựng hộp Việc nên làm hôm nay",
    description: "07:45 mỗi ngày gom việc nên làm từ PMax / Search / Meta / Sức khoẻ đo lường / Phiên xử lý / NBA, chia 3 loại (số đo sai → lãng phí → cơ hội), gộp việc cùng loại, xếp theo tiền",
    cronExpr: "45 0 * * *",
    intervalLabel: "Hằng ngày 07:45 giờ VN (00:45 UTC)",
    riskLevel: "low",
    endpoint: "/api/cron/inbox-build",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET"],
    manualTriggerAllowed: true,
    maxDurationSec: 300,
    riskNote: "chỉ đọc Google Ads / Meta (~6 truy vấn Google + 2 lượt Meta mỗi công ty); không ghi gì lên tài khoản",
    schedulingStatus: "auto",
  },
  {
    id: "inbox_digest",
    displayName: "Top 5 việc sáng — Teams kênh Ads",
    description: "08:10 mỗi ngày gửi 5 việc ưu tiên nhất (tối đa 2 việc / nguồn) vào kênh Teams của team Ads (TEAMS_WEBHOOK_ADS). Chưa đặt biến thì không gửi, việc vẫn ở trang Việc hôm nay",
    cronExpr: "10 1 * * *",
    intervalLabel: "Hằng ngày 08:10 giờ VN (01:10 UTC)",
    riskLevel: "low",
    endpoint: "/api/cron/inbox-digest",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET"],
    manualTriggerAllowed: true,
    maxDurationSec: 300,
    riskNote: "đọc ảnh chụp hộp việc; gửi 1 thẻ Teams",
    schedulingStatus: "auto",
  },
  {
    id: "write_outcomes",
    displayName: "Đo lại mọi lần ghi (7 / 14 ngày)",
    description: "09:15 mỗi ngày gom mọi lần tool ghi lên tài khoản (Search, PMax, bật/tắt, ngân sách, tự động…) và đo lại lần ghi tới mốc 7/14 ngày: CPA trước → sau, đã trừ biến động chung cả tài khoản. Mốc 14 ngày ra XẤU thì báo Teams",
    cronExpr: "15 2 * * *",
    intervalLabel: "Hằng ngày 09:15 giờ VN (02:15 UTC)",
    riskLevel: "low",
    endpoint: "/api/cron/write-outcomes",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET"],
    manualTriggerAllowed: true,
    maxDurationSec: 300,
    riskNote: "chỉ đọc Google Ads / Meta (2 truy vấn mỗi khoảng ngày, Meta tối đa 12 khoảng/lượt); không ghi gì lên tài khoản",
    schedulingStatus: "auto",
  },
  {
    id: "lead_flow_morning",
    displayName: "Báo sáng — đường lead form ↔ CRM",
    description: "8:00 mỗi ngày gửi tình trạng từng đường form → CRM (bình thường / ĐỨT, lead cuối, hôm qua bao nhiêu form/lead) kể cả khi bình thường — không nhận được tin sáng là có chuyện với chính tool",
    cronExpr: "0 1 * * *",
    intervalLabel: "Hằng ngày 08:00 giờ VN (01:00 UTC)",
    riskLevel: "low",
    endpoint: "/api/cron/lead-flow-morning",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET"],
    manualTriggerAllowed: true,
    maxDurationSec: 60,
    riskNote: "chỉ đọc pixel + Odoo; gửi 1 tin Teams (thiếu Teams thì Telegram) kênh cảnh báo hệ thống",
    schedulingStatus: "auto",
  },
  {
    id: "lead_flow_watch",
    displayName: "Canh đường lead — form trên web ↔ lead trong CRM",
    description: "Mỗi 2 giờ so số lượt gửi form trên pixel với lead Odoo theo nguồn; có form mà không có lead quá ngưỡng → báo Teams kênh IT (1 lần/ngày/đường), báo lại khi nối lại",
    cronExpr: "15 */2 * * *",
    intervalLabel: "2 giờ một lần",
    riskLevel: "low",
    endpoint: "/api/cron/lead-flow-watch",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET"],
    manualTriggerAllowed: true,
    maxDurationSec: 60,
    riskNote: "chỉ đọc pixel /stats (1 lượt Meta/đường) + Odoo crm.lead; ghi data/lead-flows.json. Sinh ra từ sự cố 25/09: form vẫn gửi mà Odoo không có lead 3 ngày, không ai biết",
    schedulingStatus: "auto",
  },
  {
    id: "playbook_outcomes",
    displayName: "Sổ kinh nghiệm — chấm kết quả áp dụng (14/28 ngày)",
    description: "Chiến dịch tạo có dùng kinh nghiệm → sau 14 và 28 ngày so chi phí/kết quả với các chiến dịch cùng sản phẩm cùng kỳ; ghi xác nhận/bác bỏ; bị bác 2 lần thì hạ kinh nghiệm tự dùng xuống gợi ý",
    cronExpr: "30 22 * * *",
    intervalLabel: "Hằng ngày 05:30 giờ VN (22:30 UTC)",
    riskLevel: "low",
    endpoint: "/api/cron/playbook-outcomes",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET"],
    manualTriggerAllowed: true,
    maxDurationSec: 300,
    riskNote: "chỉ đọc Meta (1 lượt/kỳ) + Google Ads + Odoo tuỳ chọn; ghi data/playbook/outcomes.json",
    schedulingStatus: "auto",
  },
  {
    id: "measure_monitor",
    displayName: "Giám sát đo lường — so hằng ngày, báo Teams khi đổi",
    description: "Chạy lại Chẩn đoán gắn thẻ + Sức khoẻ đo lường, so với hôm trước; chỉ báo Teams khi có hỏng mới / đã khỏi / GTM đổi bản",
    cronExpr: "0 2 * * *",
    intervalLabel: "Hằng ngày 09:00 giờ VN (02:00 UTC)",
    riskLevel: "low",
    endpoint: "/api/cron/measure-monitor",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET"],
    manualTriggerAllowed: true,
    maxDurationSec: 300,
    riskNote: "chỉ đọc Meta + Google Ads + GTM công khai + Odoo (~10 lượt gọi Meta/công ty); ghi data/measure-snapshots/; gửi Teams khi có thay đổi",
    schedulingStatus: "auto",
  },
  {
    id: "case_remeasure",
    displayName: "Xử lý chiến dịch — đo lại 7/14 ngày",
    description: "Đo lại chi phí/đơn của các phiên đã thực hiện tới mốc 7 và 14 ngày; không cải thiện thì mở lại phiên",
    cronExpr: "0 1 * * *",
    intervalLabel: "Hằng ngày 08:00 giờ VN (01:00 UTC)",
    riskLevel: "low",
    endpoint: "/api/cron/case-remeasure",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET"],
    manualTriggerAllowed: true,
    maxDurationSec: 120,
    riskNote: "chỉ đọc Google Ads + Meta; ghi kết quả vào data/cases/; nhắc Microsoft Teams việc giao người quá 3 ngày khi đặt CASE_TASK_TEAMS_WEBHOOK",
    schedulingStatus: "auto",
  },
  {
    id: "nba_engine",
    displayName: "NBA Engine (Main Orchestrator)",
    description: "Evaluates automation rules, runs AI learning, generates next-best-actions, tracks change ROI",
    cronExpr: "0 */6 * * *",
    intervalLabel: "Every 6h",
    riskLevel: "high",
    endpoint: "/api/cron",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET", "META_ACCESS_TOKEN"],
    manualTriggerAllowed: true,
    maxDurationSec: 60,
    riskNote: "auto-applies ad mutations when NBA_AUTO_APPLY=on",
    schedulingStatus: "auto",
  },
  {
    id: "automation_sim_apply",
    retired: "Chỉ chạy tay, chưa từng chạy — NBA Engine (6 giờ/lần) đã chạy luật tự động",
    displayName: "Automation Sim + Auto-Apply",
    description: "Simulates automation rules against live campaigns, applies safe actions per NBA_AUTO_APPLY policy",
    cronExpr: "0 */6 * * *",
    intervalLabel: "Every 6h (manual only)",
    riskLevel: "high",
    endpoint: "/api/cron/automation-sim-apply",
    httpMethod: "POST",
    requiredEnv: ["CRON_SECRET", "META_ACCESS_TOKEN"],
    manualTriggerAllowed: true,
    maxDurationSec: 60,
    riskNote: "fires real Meta API mutations when NBA_AUTO_APPLY=on — simulation output is meant to be human-reviewed before relying on this running unattended",
    schedulingStatus: "manual_only",
  },
  {
    id: "google_monitor",
    retired: "Chỉ chạy tay, chưa từng chạy — thay bằng Alert Engine Scan + X-quang Search/PMax; nút ở tab Tự động hoá vẫn dùng được",
    displayName: "Google Ads Monitor",
    description: "Monitors Google Ads campaign performance and budget pacing",
    cronExpr: "0 */6 * * *",
    intervalLabel: "Every 6h (manual only)",
    riskLevel: "medium",
    endpoint: "/api/automation/google/monitor",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET", "GOOGLE_ADS_REFRESH_TOKEN"],
    manualTriggerAllowed: true,
    maxDurationSec: 30,
    schedulingStatus: "manual_only",
  },
  {
    id: "google_budget_optimizer",
    retired: "Chỉ chạy tay, chưa từng chạy — nút ở tab Tự động hoá vẫn dùng được",
    displayName: "Google Budget Optimizer",
    description: "Daily rebalances Google Ads budget across campaigns based on performance",
    cronExpr: "0 6 * * *",
    intervalLabel: "Daily 6AM (manual only)",
    riskLevel: "high",
    endpoint: "/api/automation/google/budget-optimizer",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET", "GOOGLE_ADS_REFRESH_TOKEN"],
    manualTriggerAllowed: true,
    maxDurationSec: 60,
    riskNote: "modifies Google Ads campaign budgets — previously manualTriggerAllowed:false with no schedule wired, making it unreachable by anyone; fixed 2026-07-13 to at least be manually runnable",
    schedulingStatus: "manual_only",
  },
  {
    id: "quality_score_mbc",
    displayName: "Quality Score — MBC",
    description: "Fetches Google Ads quality scores for MBC campaigns",
    cronExpr: "30 0 * * *",
    intervalLabel: "Hằng ngày 07:30 (giờ VN)",
    riskLevel: "low",
    endpoint: "/api/google/toolkit/quality-score?company=MBC",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET", "GOOGLE_ADS_REFRESH_TOKEN", "GOOGLE_ADS_CUSTOMER_ID_MBC"],
    manualTriggerAllowed: true,
    maxDurationSec: 30,
    schedulingStatus: "auto",
    riskNote: "ghi mốc QS hằng ngày cho cột xu hướng + cảnh báo QS tụt của digest; trước 2026-08-19 là manual_only nên lịch sử chỉ có vào ngày có người mở trang Toolkit",
  },
  {
    id: "quality_score_mbi",
    displayName: "Quality Score — MBI",
    description: "Fetches Google Ads quality scores for MBI campaigns",
    cronExpr: "30 0 * * *",
    intervalLabel: "Hằng ngày 07:30 (giờ VN)",
    riskLevel: "low",
    endpoint: "/api/google/toolkit/quality-score?company=MBI",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET", "GOOGLE_ADS_REFRESH_TOKEN", "GOOGLE_ADS_CUSTOMER_ID_MBI"],
    manualTriggerAllowed: true,
    maxDurationSec: 30,
    schedulingStatus: "auto",
    riskNote: "ghi mốc QS hằng ngày cho cột xu hướng + cảnh báo QS tụt của digest; trước 2026-08-19 là manual_only nên lịch sử chỉ có vào ngày có người mở trang Toolkit",
  },
  {
    id: "weekly_report",
    displayName: "Báo cáo quản lý tuần (Đợt 15c)",
    description: "Thứ Hai 08:30: tiền & kết quả từng công ty (so tuần trước, TB 4 tuần), số đáng tin tới đâu, tool đã ghi gì + đo lại, việc tồn, thử nghiệm — thẻ Teams kênh Ads + lưu trang Báo cáo tuần",
    cronExpr: "30 1 * * 1",
    intervalLabel: "Thứ Hai 08:30 (giờ VN)",
    riskLevel: "low",
    endpoint: "/api/cron/weekly-report",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET"],
    manualTriggerAllowed: true,
    maxDurationSec: 300,
    riskNote: "Chỉ đọc + gửi Teams. Thiếu TEAMS_WEBHOOK_ADS thì vẫn lưu trang, không gửi",
    schedulingStatus: "auto",
  },
  {
    id: "alerts_digest",
    retired: "Gửi qua Telegram — đã ngừng dùng Telegram (29/09)",
    displayName: "Alerts Digest",
    description: "Sends daily digest of pending alerts via Telegram",
    cronExpr: "0 1 * * *",
    intervalLabel: "Daily 1AM",
    riskLevel: "medium",
    endpoint: "/api/alerts/digest",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET", "TELEGRAM_BOT_TOKEN"],
    manualTriggerAllowed: true,
    maxDurationSec: 30,
    schedulingStatus: "auto",
  },
  {
    id: "decision_memory_eval",
    displayName: "Decision Memory Evaluator",
    description: "Closes overdue evaluation windows, rolls up outcomes, and prunes expired learning signals",
    cronExpr: "0 3 * * *",
    intervalLabel: "Daily 3AM",
    riskLevel: "low",
    endpoint: "/api/cron/decision-memory-eval",
    httpMethod: "POST",
    requiredEnv: ["CRON_SECRET"],
    manualTriggerAllowed: true,
    maxDurationSec: 30,
    riskNote: "closes NBA's confidence-learning feedback loop — left unscheduled, outcome evaluation silently never completes; wired into docker-entrypoint.sh 2026-07-13",
    schedulingStatus: "auto",
  },
  {
    id: "leads_notify",
    displayName: "Lead Notify — matbao.in → Teams",
    description: "Polls Odoo CRM for new leads with source matbao.in, sends Teams card notification in real-time",
    cronExpr: "*/5 * * * *",
    intervalLabel: "Every 5m",
    riskLevel: "low",
    endpoint: "/api/cron/leads-notify",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET", "ODOO_LOGIN", "ODOO_API_KEY", "TEAMS_WEBHOOK_MATBAOIN"],
    manualTriggerAllowed: true,
    maxDurationSec: 20,
    schedulingStatus: "auto",
  },
  {
    id: "orders_notify",
    displayName: "Order Notify — matbao.in → Teams",
    description: "Polls Odoo for new sale orders (source: Đơn hàng MBI online), sends Teams card per order",
    cronExpr: "*/5 * * * *",
    intervalLabel: "Every 5m",
    riskLevel: "low",
    endpoint: "/api/cron/orders-notify",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET", "ODOO_LOGIN", "ODOO_API_KEY", "TEAMS_WEBHOOK_ORDERS_MATBAOIN"],
    manualTriggerAllowed: true,
    maxDurationSec: 20,
    schedulingStatus: "auto",
  },
  {
    id: "kpi_report",
    retired: "Gửi qua Telegram — đã ngừng dùng Telegram (29/09)",
    displayName: "KPI Report — cuối ngày → Telegram",
    description: "Gửi báo cáo KPI marketing cuối ngày (Company P&L MBC + MBI) qua bot Telegram KPI",
    cronExpr: "55 16 * * *",
    intervalLabel: "Daily 23:55 (giờ VN)",
    riskLevel: "low",
    endpoint: "/api/cron/kpi-report",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET", "TELEGRAM_KPI_BOT_TOKEN"],
    manualTriggerAllowed: true,
    maxDurationSec: 60,
    schedulingStatus: "auto",
  },
  {
    id: "ab_test_auto_stop",
    displayName: "A/B Test Auto-Stop",
    description: "Phát hiện cặp ad A/B (2 ad ACTIVE cùng ad set) có ý nghĩa thống kê (z-test tỷ lệ chuyển đổi), báo Teams IT và tự pause ad thua nếu bật auto_apply (lưu dấu vết để đo lại 7/14 ngày)",
    cronExpr: "30 1 * * *",
    intervalLabel: "Daily 08:30 (giờ VN)",
    riskLevel: "high",
    endpoint: "/api/cron/ab-test-auto-stop",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET", "META_ACCESS_TOKEN"],
    manualTriggerAllowed: true,
    maxDurationSec: 60,
    riskNote: "chỉ tự pause ad thật khi AB_TEST_AUTO_STOP_MODE=auto_apply — mặc định dry_run (chỉ đề xuất)",
    schedulingStatus: "auto",
  },
  {
    id: "improvements_auto_apply",
    displayName: "Improvements Auto-Apply",
    description: "Áp dụng tự động các Improvement đã đánh dấu canAutoApply (PAUSE_KEYWORD, UPDATE_BUDGET, UPDATE_TARGET_CPA, ADD_NEGATIVE, UPDATE_DEVICE_BID) nếu bật auto_apply; có ghi thật thì báo Teams IT + lưu dấu vết để đo lại 7/14 ngày",
    cronExpr: "0 2 * * *",
    intervalLabel: "Daily 09:00 (giờ VN)",
    riskLevel: "high",
    endpoint: "/api/cron/improvements-auto-apply",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET", "GOOGLE_ADS_REFRESH_TOKEN"],
    manualTriggerAllowed: true,
    maxDurationSec: 60,
    riskNote: "chỉ tự áp dụng mutation thật khi IMPROVEMENTS_AUTO_APPLY_MODE=auto_apply — mặc định dry_run (chỉ đề xuất)",
    schedulingStatus: "auto",
  },
  {
    id: "alert_scan",
    displayName: "Alert Engine Scan",
    description: "Gathers live CPL/spend-spike/zero-conversion/creative-fatigue metrics per campaign and runs them through ALERT_RULES — read-only, no ad mutations. Feeds data/alerts.json + the notification bell + Alerts Digest. Also generates root-cause diagnosis (lib/root-cause.ts) for new CPL alerts.",
    cronExpr: "*/30 * * * *",
    intervalLabel: "Every 30 min",
    riskLevel: "low",
    endpoint: "/api/cron/alert-scan",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET", "META_ACCESS_TOKEN"],
    manualTriggerAllowed: true,
    maxDurationSec: 45,
    riskNote: "read-only (creates Alert records + Telegram notice only, never mutates campaigns) — moved to auto 2026-07-27 by explicit request; not independently live-verified against a real ad account, low-risk given read-only nature",
    schedulingStatus: "auto",
  },
  {
    id: "policy_radar_scan",
    displayName: "Policy Radar Scan",
    description: "Fetches the auto-fetchable Policy Radar sources (Google Ads Policy Help + Dev Blog), diffs against the last snapshot, drafts + files a PolicyRadarItem via Gemini on change, and sends a Telegram alert. Read-only against Google's pages — never mutates anything outside this app's own data files. Meta sources stay manual (JS-rendered shell, no headless browser in this app).",
    cronExpr: "0 1 * * 1,4",
    intervalLabel: "Thứ 2 + Thứ 5, 08:00 giờ VN",
    riskLevel: "low",
    endpoint: "/api/cron/policy-radar-scan",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET"],
    manualTriggerAllowed: true,
    maxDurationSec: 45,
    riskNote: "read-only external fetch only — no ad account access, no mutation of anything outside data/policy-radar-*.json",
    schedulingStatus: "auto",
  },
  {
    id: "job_health_monitor",
    displayName: "Job Health Monitor — Lead/Order Notify → Teams",
    description: "Canh leads_notify và orders_notify (thẻ Teams lead/đơn hàng thời gian thực): job im lặng quá hạn hoặc lần chạy gần nhất lỗi thì báo Teams kênh IT, nhắc lại mỗi 2h tới khi hết sự cố, báo tiếp khi đã ổn lại. Không đụng Odoo — chỉ đọc lịch sử chạy đã ghi sẵn (lib/jobs/store.ts).",
    cronExpr: "*/10 * * * *",
    intervalLabel: "Every 10m",
    riskLevel: "low",
    endpoint: "/api/cron/job-health-monitor",
    httpMethod: "GET",
    requiredEnv: ["CRON_SECRET", "TEAMS_WEBHOOK_OPS_ALERTS"],
    manualTriggerAllowed: true,
    maxDurationSec: 15,
    schedulingStatus: "auto",
  },
];

export const JOBS_BY_ID = Object.fromEntries(
  JOB_REGISTRY.map(j => [j.id, j]),
) as Record<JobId, JobDescriptor>;

export function getJobDescriptor(id: JobId): JobDescriptor {
  return JOBS_BY_ID[id];
}

/** Job còn dùng (bỏ job đã ngừng) — trang Jobs, điều phối, canh sức khoẻ đều dùng danh sách này. */
export const ACTIVE_JOBS = JOB_REGISTRY.filter((j) => !j.retired)
